config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get 'static_pages/about'
  root 'static_pages#home'

  get '/about', to: 'static_pages#about'

  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])

    if @person.update(people_params)
      redirect_to people_path
    else
      render :edit
    end
  end

  def destroy
    Person.find(params[:id]).destroy
    redirect_to people_path
  end

  def create
    @person = Person.new(people_params)

    if @person.save
      redirect_to people_path
    else
      render :new
    end
  end

  private

    def people_params
      params.require(:person).permit(:name, :age, :hair_color, :eye_color, :gender, :alive)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'About', about_path %>
<%= link_to 'People', people_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PeopleApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/people/delete.html.erb
<h1>People#delete</h1>
<p>Find me in app/views/people/delete.html.erb</p>

app/views/people/edit.html.erb
<h1>Edit Person</h1>
<%= form_for @person do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :age %>
    <%= f.text_field :age %>

    <%= f.label :hair_color %>
    <%= f.text_field :hair_color %>

    <%= f.label :eye_color %>
    <%= f.text_field :eye_color %>

    <%= f.label :gender %>
    <%= f.text_field :gender %>

    <%= f.label :alive %>
    <%= f.text_field :alive %>

    <%= f.submit %>
<% end %>

app/views/people/index.html.erb
<h1> Pages </h1>
<p><%= link_to 'New person', new_person_path %></p>

<h1> People </h1>
<% @people.each do |person| %>
    <h2><%= person.name %></h2>
    <%= link_to 'Show Person', person_path(person) %>
    <%= link_to 'Edit person', edit_person_path(person) %>
    <%= link_to 'Destroy Person', person, method: :delete %>
<% end %>

app/views/people/new.html.erb
<h1>New Person</h1>
<%= form_for @person do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :age %>
    <%= f.text_field :age %>

    <%= f.label :hair_color %>
    <%= f.text_field :hair_color %>

    <%= f.label :eye_color %>
    <%= f.text_field :eye_color %>

    <%= f.label :gender %>
    <%= f.text_field :gender %>

    <%= f.label :alive %>
    <%= f.text_field :alive %>

    <%= f.submit %>
<% end %>

app/views/people/show.html.erb
<h1><%= @person.name %></h1>
<h4><%= @person.age %></h1>
<h4><%= @person.hair_color %></h1>
<h4><%= @person.eye_color %></h1>
<h4><%= @person.gender %></h1>
<h4><%= @person.alive %></h1>
<%= link_to 'Back', people_path %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>